# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='eagles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='skinsgross',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='skinsnet',
            field=models.BooleanField(default=False),
        ),
    ]
