# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180821_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='gross',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='net',
            field=models.BooleanField(default=True),
        ),
    ]
