# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180822_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=40)),
                ('handicap', models.SmallIntegerField(blank=True, default=0)),
                ('hole1score', models.SmallIntegerField(blank=True, default=0)),
                ('hole2score', models.SmallIntegerField(blank=True, default=0)),
                ('hole3score', models.SmallIntegerField(blank=True, default=0)),
                ('hole4score', models.SmallIntegerField(blank=True, default=0)),
                ('hole5score', models.SmallIntegerField(blank=True, default=0)),
                ('hole6score', models.SmallIntegerField(blank=True, default=0)),
                ('hole7score', models.SmallIntegerField(blank=True, default=0)),
                ('hole8score', models.SmallIntegerField(blank=True, default=0)),
                ('hole9score', models.SmallIntegerField(blank=True, default=0)),
                ('hole10score', models.SmallIntegerField(blank=True, default=0)),
                ('hole11score', models.SmallIntegerField(blank=True, default=0)),
                ('hole12score', models.SmallIntegerField(blank=True, default=0)),
                ('hole13score', models.SmallIntegerField(blank=True, default=0)),
                ('hole14score', models.SmallIntegerField(blank=True, default=0)),
                ('hole15score', models.SmallIntegerField(blank=True, default=0)),
                ('hole16score', models.SmallIntegerField(blank=True, default=0)),
                ('hole17score', models.SmallIntegerField(blank=True, default=0)),
                ('hole18score', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'TeamLeaderboards',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='tag',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='events.Player'),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='events.Player'),
        ),
    ]
