# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180822_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole10score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole11score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole12score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole13score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole14score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole15score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole16score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole17score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole18score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole1score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole2score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole3score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole4score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole5score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole6score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole7score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole8score',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='hole9score',
        ),
    ]
