# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180822_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaderboard',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='events.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='teamleaderboard',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='events.Leaderboard'),
        ),
    ]
