# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180822_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='netscoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='teamscoring',
            field=models.BooleanField(default=False),
        ),
    ]
