# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180823_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='password',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
