# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180926_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Handicap', unique=True),
        ),
    ]
