# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_teamleaderboard_handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='netteamscoring',
            field=models.BooleanField(default=False),
        ),
    ]
